### PR TITLE
Rename README.md to README.me

### PR DESCRIPTION
**Pull request by manishaarya9899359346**

### CODE REVIEW

**Comment by manishaarya9899359346** [comment]
Can uh help.again

**Comment by manishaarya9899359346** [comment]
Bit this time.number is change 9899359346 and it's iphone

**Comment by manishaarya9899359346** [comment]
Please can uh make it now please

**Comment by manishaarya9899359346** [comment]
Is anyone there @jardaSnajdr

**Comment by xdarkki** [comment]
That makes no sense

**Comment by manishaarya9899359346** [comment]
#

> That makes no sense

Sense Teri gand me naad dunga bhen k.lode ye notifications nhejna band kr gandu Teri Maa chodi h kya Maine Jo.ohone hack krga mera bar bar ye Kaun.lagye h Teri bhen k.lode Randi ke

**Comment by manishaarya9899359346** [comment]
Isko.toh na kahi kuch pr Teri jarur maa.chod dunga Randi l.madrasi bawling gand

**Comment by manishaarya9899359346** [comment]
Saale ghr me nikal. Ke gand pe wo.sote marunga yaad rkhega

**Comment by manishaarya9899359346** [comment]
Teri been.ka bhoada

**Comment by manishaarya9899359346** [comment]
Mujhe Pata thha merefb oe na mile thhe been m nmbr de aur baski na.ho mere le or call krle nhen ke land

**Comment by manishaarya9899359346** [comment]
1:22:01 AM: Build ready to start
1:22:05 AM: build-image version: cd0a67ec27b8bcd87e2a257fe5ebcf1900a8021d (focal)
1:22:05 AM: buildbot version: f3871d4c438bbd4f48a8f44a50bec7489430735e
1:22:05 AM: Fetching cached dependencies
1:22:05 AM: Failed to fetch cache, continuing with build
1:22:05 AM: Starting to prepare the repo for build
1:22:06 AM: No cached dependencies found. Cloning fresh repo
1:22:06 AM: git clone --filter=blob:none https://github.com/wwebjs/wwebjs.dev
1:22:06 AM: Preparing Git Reference pull/26/head
1:22:06 AM: Parsing package.json dependencies
1:22:08 AM: Starting to install dependencies
1:22:08 AM: Python version set to 3.8
1:22:08 AM: Attempting Ruby version 2.7.2, read from environment
1:22:09 AM: Using Ruby version 2.7.2
1:22:09 AM: Started restoring cached go cache
1:22:09 AM: Finished restoring cached go cache
1:22:09 AM: Installing Go version 1.19.5 (requested 1.19.5)
1:22:14 AM: go version go1.19.5 linux/amd64
1:22:14 AM: Using PHP version 8.0
1:22:15 AM: v16.20.0 is already installed.
1:22:15 AM: Now using node v16.20.0 (npm v8.19.4)
1:22:15 AM: Enabling Node.js Corepack
1:22:16 AM: Started restoring cached build plugins
1:22:16 AM: Finished restoring cached build plugins
1:22:16 AM: Started restoring cached corepack dependencies
1:22:16 AM: Finished restoring cached corepack dependencies
1:22:16 AM: No npm workspaces detected
1:22:16 AM: Started restoring cached node modules
1:22:16 AM: Finished restoring cached node modules
1:22:16 AM: Installing npm packages using npm version 8.19.4
1:22:43 AM: npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
1:22:43 AM: npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
1:22:43 AM: npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
1:22:44 AM: npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
1:22:45 AM: npm WARN deprecated har-validator@5.1.5: this library is no longer supported
1:22:45 AM: npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
1:22:45 AM: npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
1:22:46 AM: npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
1:22:46 AM: npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
1:22:47 AM: npm WARN deprecated docsearch.js@2.6.3: This package has been deprecated and is no longer maintained. Please use @docsearch/js.
1:22:48 AM: npm WARN deprecated mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
1:22:48 AM: npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
1:22:48 AM: npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
1:22:49 AM: npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest
1:22:51 AM: added 1352 packages, and audited 1353 packages in 35s
1:22:51 AM: 112 packages are looking for funding
1:22:51 AM:   run `npm fund` for details
1:22:51 AM: 37 vulnerabilities (1 low, 11 moderate, 22 high, 3 critical)
1:22:51 AM: To address issues that do not require attention, run:
1:22:51 AM:   npm audit fix
1:22:51 AM: To address all issues (including breaking changes), run:
1:22:51 AM:   npm audit fix --force
1:22:51 AM: Run `npm audit` for details.
1:22:51 AM: npm packages installed
1:22:51 AM: Install dependencies script success
1:22:51 AM: Starting build script
1:22:52 AM: Detected 1 framework(s)
1:22:52 AM: "vuepress" at version "1.9.9"
1:22:52 AM: Section completed: initializing
1:22:54 AM: ​
1:22:54 AM:   Netlify Build                                                 
1:22:54 AM: ────────────────────────────────────────────────────────────────
1:22:54 AM: ​
1:22:54 AM: ❯ Version
1:22:54 AM:   @netlify/build 29.10.1
1:22:54 AM: ​
1:22:54 AM: ❯ Flags
1:22:54 AM:   baseRelDir: true
1:22:54 AM:   buildId: 6456afe10903960008adf0cf
1:22:54 AM:   deployId: 6456afe10903960008adf0d1
1:22:54 AM: ​
1:22:54 AM: ❯ Current directory
1:22:54 AM:   /opt/build/repo
1:22:54 AM: ​
1:22:54 AM: ❯ Config file
1:22:54 AM:   No config file was defined: using default values.
1:22:54 AM: ​
1:22:54 AM: ❯ Context
1:22:54 AM:   deploy-preview
1:22:54 AM: ​
1:22:54 AM:   1. Build command from Netlify app                             
1:22:54 AM: ────────────────────────────────────────────────────────────────
1:22:54 AM: ​
1:22:54 AM: $ npm run docs:build
1:22:54 AM: > wwebjs.dev@1.0.0 docs:build
1:22:54 AM: > vuepress build src
1:22:55 AM: wait Extracting site metadata...
1:22:55 AM: tip Apply theme vuepress-theme-yuu (extends @vuepress/theme-default) ...
1:22:55 AM: tip Apply plugin container (i.e. "vuepress-plugin-container") ...
1:22:55 AM: tip Apply plugin @vuepress/last-updated (i.e. "@vuepress/plugin-last-updated") ...
1:22:55 AM: tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
1:22:55 AM: tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
1:22:55 AM: tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
1:22:55 AM: tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
1:22:55 AM: tip Apply plugin yuu-theme-plugin ...
1:22:55 AM: tip Apply plugin @vuepress/back-to-top (i.e. "@vuepress/plugin-back-to-top") ...
1:22:55 AM: tip Apply plugin @vuepress/medium-zoom (i.e. "@vuepress/plugin-medium-zoom") ...
1:22:55 AM: tip Apply plugin code-copy (i.e. "vuepress-plugin-code-copy") ...
1:22:55 AM: [info] [webpackbar] Compiling Client
1:22:55 AM: [info] [webpackbar] Compiling Server
1:23:02 AM: [success] [webpackbar] Server: Compiled successfully in 6.98s
1:23:06 AM: [success] [webpackbar] Client: Compiled successfully in 10.49s
1:23:06 AM: wait Rendering static HTML...
1:23:06 AM: [vuepress] No matching page found for sidebar item "/guide/"
1:23:06 AM: [vuepress] No matching page found for sidebar item "/guide/"
1:23:06 AM: [vuepress] No matching page found for sidebar item "/guide/"
1:23:06 AM: [Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'match')"
1:23:06 AM: found in
1:23:06 AM: ---> <SidebarLinks>
1:23:06 AM:        <DropdownTransition>
1:23:06 AM:          <SidebarGroup>
1:23:06 AM:            <SidebarLinks>
1:23:06 AM:              <Sidebar>
1:23:06 AM:                <Layout>
1:23:06 AM:                  <Layout>
1:23:06 AM:                    <GlobalLayout>
1:23:06 AM:                      <Root>
1:23:06 AM: [vuepress] No matching page found for sidebar item "/guide/"
1:23:06 AM: [vuepress] No matching page found for sidebar item "/guide/"
1:23:06 AM: [vuepress] No matching page found for sidebar item "/guide/"
1:23:06 AM: [Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'match')"
1:23:06 AM: found in
1:23:06 AM: ---> <SidebarLinks>
1:23:06 AM:        <DropdownTransition>
1:23:06 AM:          <SidebarGroup>
1:23:06 AM:            <SidebarLinks>
1:23:06 AM:              <Sidebar>
1:23:06 AM:                <Layout>
1:23:06 AM:                  <Layout>
1:23:06 AM:                    <GlobalLayout>
1:23:06 AM:                      <Root>
1:23:06 AM: [vuepress] No matching page found for sidebar item "/guide/"
1:23:06 AM: [vuepress] No matching page found for sidebar item "/guide/"
1:23:06 AM: [vuepress] No matching page found for sidebar item "/guide/"
1:23:06 AM: [Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'match')"
1:23:06 AM: found in
1:23:06 AM: ---> <SidebarLinks>
1:23:06 AM:        <DropdownTransition>
1:23:06 AM:          <SidebarGroup>
1:23:07 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
1:23:06 AM:            <SidebarLinks>
1:23:06 AM:              <Sidebar>
1:23:06 AM:                <Layout>
1:23:06 AM:                  <Layout>
1:23:06 AM:                    <GlobalLayout>
1:23:06 AM:                      <Root>
1:23:06 AM: [vuepress] No matching page found for sidebar item "/guide/"
1:23:06 AM: [vuepress] No matching page found for sidebar item "/guide/"
1:23:06 AM: [vuepress] No matching page found for sidebar item "/guide/"
1:23:06 AM: [Vue warn]: Error in render: "TypeError: Cannot read properties of undefined (reading 'match')"
1:23:06 AM: found in
1:23:06 AM: ---> <SidebarLinks>
1:23:06 AM:        <DropdownTransition>
1:23:06 AM:          <SidebarGroup>
1:23:06 AM:            <SidebarLinks>
1:23:06 AM:              <Sidebar>
1:23:06 AM:                <Layout>
1:23:06 AM:                  <Layout>
1:23:06 AM:                    <GlobalLayout>
1:23:06 AM:                      <Root>
1:23:06 AM: error Error rendering /guide/authentication.html: false
1:23:06 AM: undefined
1:23:06 AM: error Error rendering /guide/handling-attachments.html: false
1:23:06 AM: undefined
1:23:06 AM: error Error rendering /guide/interfacing-with-groups.html: false
1:23:06 AM: undefined
1:23:06 AM: error Error rendering /guide/mentioning-contacts.html: false
1:23:06 AM: undefined
1:23:06 AM: TypeError: Cannot read properties of undefined (reading 'match')
1:23:06 AM:     at getHash (node_modules/@vuepress/theme-default/util/index.js:13:21)
1:23:06 AM:     at isActive (node_modules/@vuepress/theme-default/util/index.js:47:19)
1:23:06 AM:     at render (node_modules/@vuepress/theme-default/components/SidebarLink.vue:25:32)
1:23:06 AM:     at renderWithStyleInjection (node_modules/vue-loader/lib/runtime/componentNormalizer.js:83:0)
1:23:06 AM:     at createFunctionalComponent (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:4303:34)
1:23:06 AM:     at createComponent (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:4443:16)
1:23:06 AM:     at _createElement (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:2819:21)
1:23:06 AM:     at createElement$1 (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:2771:12)
1:23:06 AM:     at vm._c (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:2545:29)
1:23:06 AM:     at 1.server-bundle.js:529:10
1:23:06 AM:     at Proxy.renderList (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:1947:22)
1:23:06 AM:     at Proxy.render (node_modules/@vuepress/theme-default/components/SidebarLinks.vue:1:128)
1:23:06 AM:     at VueComponent.Vue._render (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.dev.js:2590:28)
1:23:06 AM:     at resolve (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7221:33)
1:23:06 AM:     at waitForServerPrefetch (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7105:5)
1:23:06 AM:     at renderComponentInner (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7235:5)
1:23:06 AM:     at renderComponent (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7195:9)
1:23:06 AM:     at renderNode (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7112:9)
1:23:06 AM:     at resolve (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7232:9)
1:23:06 AM:     at waitForServerPrefetch (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7105:5)
1:23:06 AM:     at renderComponentInner (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7235:5)
1:23:06 AM:     at renderComponent (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7195:9)
1:23:06 AM:     at renderNode (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7112:9)
1:23:06 AM:     at resolve (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7232:9)
1:23:06 AM:     at waitForServerPrefetch (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7105:5)
1:23:06 AM:     at renderComponentInner (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7235:5)
1:23:06 AM:     at renderComponent (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7195:9)
1:23:06 AM:     at RenderContext.renderNode (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7112:9)
1:23:06 AM:     at RenderContext.next (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:3672:37)
1:23:06 AM:     at cachedWrite (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:3547:17)
1:23:06 AM:     at renderStringNode (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7300:9)
1:23:06 AM:     at RenderContext.renderNode (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7109:9)
1:23:06 AM:     at RenderContext.next (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:3672:37)
1:23:06 AM:     at RenderContext.cachedWrite [as write] (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:3547:17)
1:23:06 AM:     at RenderContext.next (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:3677:41)
1:23:06 AM:     at RenderContext.cachedWrite [as write] (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:3547:17)
1:23:06 AM:     at RenderContext.renderNode (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7123:21)
1:23:06 AM:     at RenderContext.next (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:3672:37)
1:23:06 AM:     at RenderContext.cachedWrite [as write] (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:3547:17)
1:23:06 AM:     at RenderContext.renderNode (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7127:17)
1:23:06 AM:     at RenderContext.next (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:3672:37)
1:23:06 AM:     at RenderContext.cachedWrite [as write] (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:3547:17)
1:23:06 AM:     at RenderContext.next (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:3677:41)
1:23:06 AM:     at RenderContext.cachedWrite [as write] (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:3547:17)
1:23:06 AM:     at RenderContext.renderNode (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7127:17)
1:23:06 AM:     at RenderContext.next (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:3672:37)
1:23:06 AM:     at cachedWrite (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:3547:17)
1:23:06 AM:     at renderElement (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7343:9)
1:23:06 AM:     at RenderContext.renderNode (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:7115:9)
1:23:06 AM:     at RenderContext.next (/opt/build/repo/node_modules/vue-server-renderer/build.dev.js:3672:37)
1:23:06 AM: ​
1:23:06 AM:   "build.command" failed                                        
1:23:06 AM: ────────────────────────────────────────────────────────────────
1:23:06 AM: ​
1:23:06 AM:   Error message
1:23:06 AM:   Command failed with exit code 1: npm run docs:build (https://ntl.fyi/exit-code-1)
1:23:06 AM: ​
1:23:06 AM:   Error location
1:23:06 AM:   In Build command from Netlify app:
1:23:06 AM:   npm run docs:build
1:23:06 AM: ​
1:23:06 AM:   Resolved config
1:23:06 AM:   build:
1:23:06 AM:     command: npm run docs:build
1:23:06 AM:     commandOrigin: ui
1:23:06 AM:     environment:
1:23:06 AM:       - REVIEW_ID
1:23:06 AM:     publish: /opt/build/repo/src/.vuepress/dist
1:23:06 AM:     publishOrigin: ui
1:23:07 AM: Caching artifacts
1:23:07 AM: Started saving node modules
1:23:07 AM: Finished saving node modules
1:23:07 AM: Started saving build plugins
1:23:07 AM: Finished saving build plugins
1:23:07 AM: Started saving corepack cache
1:23:07 AM: Finished saving corepack cache
1:23:07 AM: Started saving pip cache
1:23:07 AM: Finished saving pip cache
1:23:07 AM: Started saving emacs cask dependencies
1:23:07 AM: Finished saving emacs cask dependencies
1:23:07 AM: Started saving maven dependencies
1:23:07 AM: Finished saving maven dependencies
1:23:07 AM: Started saving boot dependencies
1:23:07 AM: Finished saving boot dependencies
1:23:07 AM: Started saving rust rustup cache
1:23:07 AM: Finished saving rust rustup cache
1:23:07 AM: Started saving go dependencies
1:23:07 AM: Finished saving go dependencies
1:23:07 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
1:23:07 AM: Failing build: Failed to build site
1:23:08 AM: Finished processing build request in 1m2.395s

**Comment by msscsh** [comment]
No need to use the file notation without the ".md", as the purpose of the file is to operate with Markdown on GitHub

https://stackoverflow.com/questions/8655937/what-is-the-difference-between-readme-and-readme-md-in-github-projects

**Comment by xdarkki** [comment]
> No need to use the file notation without the ".md", as the purpose of the file is to operate with Markdown on GitHub
> 
> 
> 
> https://stackoverflow.com/questions/8655937/what-is-the-difference-between-readme-and-readme-md-in-github-projects

However, nothing is processed on GitHub, all processes take place on Netlify.

**Comment by xdarkki** [comment]
> No need to use the file notation without the ".md", as the purpose of the file is to operate with Markdown on GitHub
> 
> 
> 
> https://stackoverflow.com/questions/8655937/what-is-the-difference-between-readme-and-readme-md-in-github-projects

Normally, the change would not make an error, but due to the other use of README.md in vuepress v1, it is always needed in a folder. As far as I remember, no error is generated when changing other used files (.md) and the section is simply not deployed.

**Comment by xdarkki** [comment]
Closed due to unusable.

**Pull request closed without merging**
